=pod

=head1 NAME

cupt_vs_apt - overview of things Cupt and APT differ in

=head1 ADVANTAGES

=head2 Core

=over

=item

pins can be specified also by source package

=item

correctness of APT options is checked

=back

=head2 Search

=over

=item

'search' command searches all versions of package, not policy or installed ones

=item

'search' command can search case-sensitively ('--case-sensitive' switch)

=back

=head2 Interface

=over

=item

'show' command can show release description ('--with-release-info' switch)

=item

'/<distribution' and '=<version>' suffixes can be used with 'depends' and
'rdepends' commands

=item

'policysrc' command

=item

'shell' command

=back

=head2 Managing packages

=over

=item

'satisfy' command is present

=item

two types of multi-case problem resolvers available (see L<--resolver in cupt(1)|cupt(1)/--resolver>)

=item

worker passes '--force-*' options to dpkg only when really needed, not always

=item

source versions of the same binary packages can be synchronized by resolver
(see L<option cupt::resolver::synchronize-source-versions|cupt(1)/cupt::resolver::synchronize-source-versions>)

=back

=head2 Downloading

=over

=item

LZMA-compressed index files are supported.

=item

HTTP redirects can be followed (see L<acquire::http::allow-redirects in cupt(1)|cupt(1)/acquire::http::allow-redirects>)

=item

downloading deb binary packages via debdelta(1) is supported

=back

=head1 DISADVANTAGES

=over

=item

cdrom URI type is not handled

=item

PDiffs are not supported

=back

=head1 DIFFERENT BEHAVIOR

=head2 Configuration

=over

=item

'apt::cache::allversions' defaults to 0, not 1 as in apt-cache

=item

to explicitly disable proxy, set 'acquire::<protocol>::[<host::]proxy' to "", not to "DIRECT"

=item

'acquire::<protocol>::[<host>::]proxy' options take precedence over "<protocol>_proxy" shell variables

=item

'gpgv::trustedkeyring' defaults to '/var/lib/cupt/trusted.gpg'

=back
