=pod

=encoding utf8

=head1 NAME

cupt_vs_apt - overview of things Cupt and APT differ in

=head1 FEATURE SETS

See L<cupt_tutorial/Disadvantages and advantages>.

=head1 DIFFERENT BEHAVIOR

=head2 Configuration

=over

=item

'apt::cache::allversions' defaults to 0, not 1 as in apt-cache

=item

'gpgv::trustedkeyring' defaults to '/var/lib/cupt/trusted.gpg'

=item

to prioritize compression types, use option 'cupt::update::compression-types',
not 'acquire::compression-types'

=item

to select repository indexes localizations, use option
'cupt::languages::indexes', not 'acquire::languages'

=back

=head2 Pinning

=over

=item

the difference between 'specific' and 'general' pin types is not supported

=item

an additional pin priority penalty is applied by default to NotAutomatic
releases (see 'cupt::cache::pin::addendums::not-automatic' option)

=back
